config/routes.rb
Rails.application.routes.draw do
  resources :visitors, only: [:index] do
    collection do 
      get 'display/:id' => 'visitors#display', :as => 'display'
      get 'category/:name' => 'visitors#category', :as => 'category'
      get 'download/:id' => 'visitors#download', :as => 'download'
    end
  end
  root to: 'visitors#index'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_search

  def index
    @results = @search.result.valid.recent
    @count = @results.count
    @movies = @results.page(params[:page]).per(15)
  end

  def display
    @movie = Movie.find(params[:id])
  end

  def category
    @category = Category.includes(:movies).find_by(name: params[:name])
    @search = @category.movies.ransack(params[:q])
    @results = @search.result.valid.recent
    @movies = @results.page(params[:page]).per(15)
  end

  def download
    movie = Movie.find(params[:id])
    movie.count
    redirect_to movie.torrent
  end

  private
    def set_search
      @search = Movie.ransack(params[:q])
    end
end

app/views/visitors/_movies.haml
%table.table.table-striped
  %thead
    %tr       
      %th.col-md-4= sort_link @search, :title, "Title"
      %th.col-md-3 Genre
      %th.col-md-2= sort_link @search, :rating, "Rating", default_order: :desc
      %th.col-md-1 DL Count
      %th.col-md-2 Link
  %tbody
    - @movies.each do |movie|          
      %tr
        %td.title.col-md-4
          = movie.title
        %td.genre.col-md-3
          - movie.categories.each do |genre|
            = link_to genre_status(genre.name), category_visitors_path(genre.name)
        %td.rating.col-md-2
          = info_value(movie.rating)
        %td.download_count.col-md-1
          = movie.download_count
        %td.link.col-md-2
          = link_to "View Details and Download", display_visitors_path(movie), class: 'btn btn-primary btn-sm'

= paginate @movies
        
      

app/views/visitors/category.html.haml
.container
  .row.content
    .col-sm-12#display-list
      %h2 Search for "#{@category.name}" category
      = render 'movies'

app/views/visitors/display.html.haml
.container
  .entry
    .row
      .movie_image.col-sm-12.col-md-4
        = image_tag @movie.image, class: 'img-responsive', height: "600px", width: "400px"
    
      .col-sm-12.col-md-8.content
        .title_header.row
          %h2.col-md-7= @movie.title        
          .button_torrent.col-md-4.col-md-offset-1
            = link_to "Torrent Download", download_visitors_path(@movie), class: 'btn btn-primary btn-default'
            = link_to "Back", :back, class: 'btn btn-primary btn-default'
  
        .description
          %p
            %strong
              Plot:
            = info_value(@movie.plot)

          %ul
            %li
              %strong
                IMDB Link:
              - if @movie.imdb.present?
                = link_to @movie.imdb, @movie.imdb
              - else
                None 
            %li
              %strong
                Genre: 
              - @movie.categories.each do |genre|
                = genre.name.titleize
            %li
              %strong
                Size:
              = info_value(@movie.size)
            %li
              %strong
                Quality:
              = info_value(@movie.quality)
            %li
              %strong
                Language:
              = info_value(@movie.language)

        .embed-responsive.embed-responsive-16by9
          = embed(@movie.youtube_url)

app/views/visitors/index.html.haml
.container
  .content
    #display-list
      -if params[:q] && params[:q].values.reject(&:blank?).any?      
        %h2
          Search
          = pluralize(@count, 'Result') 
      = render 'movies'  